# Generated by Django 5.1.1 on 2024-09-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=700, null=True)),
                ('duration', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'movies',
            },
        ),
    ]
